import Head from 'next/head'
import { Nunito } from 'next/font/google'
import { useRouter } from 'next/router'
import styles from '@/styles/Version.module.css'
import data from '@/data/versionsData'

const nunito = Nunito({ subsets: ['latin'] })

export default function VersionPage() {
	const router = useRouter();
	const handleBack = () => {
		router.back();
	}

	const version = data.find((version) => version.id === router.query.id);

	const cardBg = {
		backgroundColor: version?.bgColor
	}

	return (
		<>
			<Head>
				<title>Update - {router.query.id}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${nunito.className} ${styles.main}`}>
				<div className={styles.ctaBack}>
					<button className={styles.backButton} onClick={handleBack}>
						Back
					</button>
				</div>
				<div className={styles.wrapper} style={cardBg}>
					{router.query.slug}
					{version?.title}
					{version?.releaseDate}
					{version?.improvements.map((item,index) => (
						<div
							key={index}
						>
							{item.long}
						</div>
					))}
				</div>
			</main>
		</>
	)
}
