import Head from 'next/head'
import { Nunito } from 'next/font/google'
import CardList from '@/components/cardList'
import { useRouter } from 'next/router'

const nunito = Nunito({ subsets: ['latin'] })

export default function VersionPage() {
  const router = useRouter();
    
return (
    <>
      <Head>
        <title>Update - {router.query.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header/> */}
      <main className={`${nunito.className}`}>
        {router.query.slug}
      </main>
    </>
  )
}
