import Head from 'next/head'
import { Nunito } from 'next/font/google'
import { useRouter } from 'next/router'
import styles from '@/styles/Version.module.css'
import Link from 'next/link'

const nunito = Nunito({ subsets: ['latin'] })

export default function VersionPage() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Update - {router.query.slug}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${nunito.className} ${styles.main}`}>
				<div>
				</div>
				<div className={styles.wrapper}>
					{router.query.slug}
				</div>
			</main>
		</>
	)
}
