import Head from "next/head";
import { Nunito } from 'next/font/google'
import styles from '@/styles/Custom404.module.css'
import Link from "next/link";

const nunito = Nunito({ subsets: ['latin'] })
export default function Custom404() {
    return(
        <>
            <Head>
                <title>Update - 404 Page Not Found</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${nunito.className} ${styles.main}`}>
                <div>
                    <h1 className={styles.errorCode}> 
                        404 
                    </h1>
                    <h2 className={styles.errorStatus}>Page not found</h2>
                    <div className={styles.backLinkWrapper}>
                        <Link className={styles.backLink} href="/">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-3 h-3">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                            </svg>
                            Back
                        </Link>
                    </div>
                </div>
            </main>
        </>
    );
}