import Head from "next/head";
import { Nunito } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const nunito = Nunito({ subsets: ['latin'] })
export default function Custom404() {
    return(
        <>
            <Head>
                <title>Update - 404 Page Not Found</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${nunito.className} ${styles.main}`}>
                <div> 
                    404 
                </div>
            </main>
        </>
    );
}